<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = {
"Student": ["Aman", "Riya", "Karan", "Neha", "Rohit"],
"Attendance": [85, 90, np.nan, 75, 80],
"Marks": [78, np.nan, 65, 88, np.nan],
"Study_Hours": [3, 4, 2, np.nan, 5]

}

df = pd.DataFrame(data)

df

  Student  Attendance  Marks  Study_Hours
0    Aman        85.0   78.0          3.0
1    Riya        90.0    NaN          4.0
2   Karan         NaN   65.0          2.0
3    Neha        75.0   88.0          NaN
4   Rohit        80.0    NaN          5.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student      5 non-null      object
 1   Attendance   4 non-null      float64
 2   Marks        3 non-null      float64
 3   Study_Hours  4 non-null      float64
dtypes: float64(3), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.isna().sum()

Student        0
Attendance     1
Marks          2
Study_Hours    1
dtype: int64

In [ ]:
print("not null")
notnull = df.notna().sum().sum()
print(notnull)

print("total null")
null = df.isna().sum().sum()
print(null)

not null
16
total null
4

In [ ]:
# What % of values are missing in the entire dataframe

print((null/df.size)* 100)

20.0

In [ ]:
#what % of rows have some missing data?
total_missing = df.isna().any(axis = 1).sum()

In [ ]:
total_missing_perc =total_missing/ df.shape[0] * 100
print(total_missing_perc)

80.0

In [ ]:
#perc of missign columns
df.isna().any().sum()

np.int64(3)

In [1]:
# day 14

In [2]:
a = 100

In [3]:
b = "100"

In [4]:
a +b

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [5]:
a + int(b)

200

In [6]:
student_name = "Amit"
age = 20
marks = 87.5
is_placed = True

print(type(student_name))
print(type(age))
print(type(marks))
print(type(is_placed))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [8]:

import pandas as pd
df = pd.DataFrame({
"Name": ["Amit", "Neha", "Ravi"],
"Age": [20, 21, 19],
"Marks": [85.5, 91.0, 78.5],
"Passed": [True, True, True]
})
df

   Name  Age  Marks  Passed
0  Amit   20   85.5    True
1  Neha   21   91.0    True
2  Ravi   19   78.5    True

In [17]:
# Number of rows.
df.shape[0]

# Number of columns.
df.shape[1]

# Column names.
list(df.columns)

# Non-null counts.
df.notna().sum()

# Data types.
df.dtypes

Name       object
Age         int64
Marks     float64
Passed       bool
dtype: object

In [18]:
df = pd.DataFrame({
"Age": ["18", "19", "20", "21"]
})
print(df.dtypes)

Age    object
dtype: object

In [19]:
# change the dtype of column

In [20]:
df["Age2"] = df["Age"].astype(int)

In [21]:
df

  Age  Age2
0  18    18
1  19    19
2  20    20
3  21    21

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     4 non-null      object
 1   Age2    4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [23]:
df = pd.DataFrame({
"Marks": ["85.5", "90.0", "76.5"]
})
#Compute the average marks.

In [27]:
import numpy as np
df["Marks"] = df["Marks"].astype(float)
np.average(df["Marks"])

np.float64(84.0)

In [31]:
df = pd.DataFrame({
"Rating": [4.8, 3.6, 4.2]

})

# I want the ratings to be in int format

df["Rating"] =df["Rating"].astype(int)

df["Rating"]

0    4
1    3
2    4
Name: Rating, dtype: int64

In [32]:
df = pd.DataFrame({
"Product_ID": [101, 102, 103]
})
#convert product id to string format.

In [35]:
df["Product_ID"].astype(str)

0    101
1    102
2    103
Name: Product_ID, dtype: object

In [37]:
df = pd.DataFrame({

"Passed": [1, 0, 1, 1, 0]
}
)

In [38]:
df["Passed"]= df["Passed"].astype(bool)

In [39]:
df

   Passed
0    True
1   False
2    True
3    True
4   False

In [ ]:
# Problem: An array contains N distinct numbers from the range 0 to N,
# with one number missing. Find the missing number.

# Example: [3, 0,1]
# Output: 2

In [46]:
Example = [4,2, 0,1]

for i in range(len(Example)+1):
  if i not in Example:
    print(i)

3

In [ ]:
Problem: Find the element that occurs more than n / 2 times.
Assume such an element is guaranteed to exist.



Output:

In [60]:
Example = [3, 2, 3, 3, 1]

length = len(Example)//2

# for i in Example:
#   if i
#   \

output = []
for i in Example:
  count = Example.count(i)
  if count >=length:
    output.append(i)
print(max(output))

3

In [ ]:
Problem: Given a sorted array of distinct integers and a target,
return its index if found.
Otherwise, return the index where it should be inserted to maintain sorted order.

Example: arr = [1, 3, 5, 6], target = 2 - 1

In [73]:
arr = [1,2, 3, 4,5, 7]
target = 6
output = []

if target < arr[0]:
  print(0)
else:
  for i in range(len(arr)):
    if arr[i] == target:
      output.append(i)
    elif target >arr[i] and target< arr[i+1]:
      output.append(i+1)

  if target not in arr:
    print(len(arr) )
  else:
    print(output)

6