<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = {
"Student": ["Aman", "Riya", "Karan", "Neha", "Rohit"],
"Attendance": [85, 90, np.nan, 75, 80],
"Marks": [78, np.nan, 65, 88, np.nan],
"Study_Hours": [3, 4, 2, np.nan, 5]

}

df = pd.DataFrame(data)

df

  Student  Attendance  Marks  Study_Hours
0    Aman        85.0   78.0          3.0
1    Riya        90.0    NaN          4.0
2   Karan         NaN   65.0          2.0
3    Neha        75.0   88.0          NaN
4   Rohit        80.0    NaN          5.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student      5 non-null      object
 1   Attendance   4 non-null      float64
 2   Marks        3 non-null      float64
 3   Study_Hours  4 non-null      float64
dtypes: float64(3), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.isna().sum()

Student        0
Attendance     1
Marks          2
Study_Hours    1
dtype: int64

In [ ]:
print("not null")
notnull = df.notna().sum().sum()
print(notnull)

print("total null")
null = df.isna().sum().sum()
print(null)

not null
16
total null
4

In [ ]:
# What % of values are missing in the entire dataframe

print((null/df.size)* 100)

20.0

In [ ]:
#what % of rows have some missing data?
total_missing = df.isna().any(axis = 1).sum()

In [ ]:
total_missing_perc =total_missing/ df.shape[0] * 100
print(total_missing_perc)

80.0

In [ ]:
#perc of missign columns
df.isna().any().sum()

np.int64(3)