<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
students = pd.DataFrame({
"Name": ["A", "B", "C", "D", "E"],
"Maths": [80, np.nan, 70, 90, np.nan],
"Science": [np.nan, 75, 85, 90, 80],
"English": [70, 80, np.nan, 95, 85]
})
students

  Name  Maths  Science  English
0    A   80.0      NaN     70.0
1    B    NaN     75.0     80.0
2    C   70.0     85.0      NaN
3    D   90.0     90.0     95.0
4    E    NaN     80.0     85.0

In [ ]:
# Questions:

# Display the dataset.
students

# Find the missing-value positions.
students.isna()

# Count missing values in each subject.
students.isna().sum()

# Count all missing cells.
students.isna().sum().sum()

# Calculate missing percentages.
students.isna().sum().sum()/students.size* 100

# Display only students whose Maths marks are missing.
students[students["Maths"].isna()]["Name"]

1    B
4    E
Name: Name, dtype: object

In [ ]:
df = pd.DataFrame ({
"Joining_Date": ["2024-01-15", "2025-06-20"]
})


#create a new column with only the year of each row.

In [ ]:
arr = df["Joining_Date"].str[:4]

In [ ]:
arr

0    2024
1    2025
Name: Joining_Date, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Joining_Date  2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes

In [ ]:
df["Joining_year"] = pd.to_datetime(df["Joining_Date"])

In [ ]:
df

  Joining_Date Joining_year
0   2024-01-15   2024-01-15
1   2025-06-20   2025-06-20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Joining_Date  2 non-null      object
 1   Joining_year  2 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 164.0+ bytes

In [ ]:
# extract year in date format

In [ ]:
df["Joining_year"].dt.year

0    2024
1    2025
Name: Joining_year, dtype: int32

In [ ]:
# Problem: Two.strings are isomorphic.
# if.each .character. in.the first string .consistently .maps
# to .one .character .in .the .second .string,
# and.two .different .characters .cannot .map .to .the .same .character.

# Example: "egg" .and. "add" -> true

In [ ]:
string1 = "ab"
string2 = "cc"

dictionary = {}

for i in range(len(string1)):
  if string1[i] not in dictionary:
    dictionary[string1[i]]= string2[i]
  else:
    if dictionary[string1[i]] != string2[i]:
      print("error")

In [ ]:
# Problem: Determine whether all characters .of string .s.appear in.string.t.in.the same order,
# though.not.necessarily consecutively.

# Example: s = "ace", t="abcde"
#Output: Yes

In [ ]:
s = "ace"
t="abcde"

for i in range(len(s)):
  for j in range(len(t)):
    if s[i]==s[j]:
      break

  i =

In [ ]:
max

'abcde'

In [ ]:
# Given a positive integer N, repeatedly perform the following operation:
#- If .N.is.even, divide.it.by.2.
#-If .N.is.odd, subtract.1.from.it.
# Return.the number.of operations .required .to make.N.equal .to.zero.

# Input: 14
# .Output: 6

In [ ]:
Input = 14
count = 0
while Input != 0:
  # print(Input)
  if Input % 2 == 0:
    Input = Input/2

  else:
    Input = Input -1

  count = count + 1
print(count)

14
7.0
6.0
3.0
2.0
1.0
6

In [ ]:
# There are several chips placed at different positions on a number line.

# You can move a chip:
# - By 2 positions at a cost of 0.
# - By 1 position at a cost of 1.
# Find the minimum total cost required to move all chips to the same position.

# Input:
# position = [1, 2,3]
# Output: 0+1 = 1

In [ ]:
position = [1, 2,3,4,5,6]
lenA = len(position)
count = 0
for i in range(1,(lenA//2)+1):
  # print(i)
  for j in range(1,i+1):
    if i == j:
      count = count +1

print(count)

3

In [ ]:
Given a list of sentences,
find the maximum number of words present in any single sentence.


Words are separated by spaces.

"I love programming",
"Data structures are important",
"Practice daily"

In [ ]:
output = ["I love programming",
"Data structures are important",
"Practice daily"]

# outputtwo = output.split(" ")
# max = len(outputtwo[0])
max = 0

for i in output:
  outputtwo = i.split(" ")
  if len(outputtwo)> max:
    max = len(outputtwo)


print(max)

4

In [ ]:
Given an array of integers and an integer K,
select any K elements such that the difference between
the maximum and minimum selected elements is as small as possible.

Return this minimum difference.

Input:
nums = [9,4,1,7]
k = 2

Output: 2

In [ ]:
nums = [9,4,1,7]
k = 2


for i in range(len(nums)-1):
  for j in range(i+1,len(nums)):